"""
Django settings for django_movie project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
#Файл со всеми настройками проекта
import os


#Построенние пути к корню нашего проекта
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'duxm4&m#2rf^%*i$v5e9dapuks!jf3l@-d1p20k_e0el-hi=bg'

# SECURITY WARNING: don't run with debug turned on in production!

#Булевое значение которое включает и отключает режимы отладки проекта,если оно равно True 
#Django будет отображать подробные страницы с ошибками при выбрасовании исключений в приложении
#Когда будем розворачивать приложение на боевом сервере нужно установить на FALSE
DEBUG = True

#НЕ используеться при включенной отладке и запуске тестов, но как только мы разварачиваем приложение и устанавливаем флаг DEBUG=FALSE
#необходимо добавить домен сайта в эту настройку для того чтоыб DJANGO мог с ним работать.

ALLOWED_HOSTS = []


# Application definition
#Настройка которую мы будем изменять во всех наших проектах она указывает DJANGO какие приложение активны в нашем проекте
INSTALLED_APPS = [
    'django.contrib.admin', #сайт администирования
    'django.contrib.auth', #подсистема аунтифекации
    'django.contrib.contenttypes', #подсистема для работы с типами обьектов
    'django.contrib.sessions', #подсистема сессий
    'django.contrib.messages', #подсистема сообщений
    'django.contrib.staticfiles', #подсистема для управления статическим содержимым сайта


    'movies'
]

#Список подключенных промежуточных слоев
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#Указывает на пайтон модуль который содержит корневые шаблоны URL в приложении
ROOT_URLCONF = 'django_movie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_movie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

#Представляет собой словарь настройки для всех баз данных проекта, всегда должна быть указана хотябы одна база данных.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

#Определяет код языка по умолчанию для джанго-сайта
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

#Указывает на необходимость поддержки временных зон 
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
